name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t neoimpweb/docker-react -f Dockerfile.dev .
    - name: Test the Docker image
      run: docker run -e CI=true neoimpweb/docker-react npm run test