name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# env:
#   ## DockerHub
#   # DOCKER_HUB_USERNAME: woohobi
#   # AWS & Elastic Bean Stalk
#   AWS_REGION: ap-northeast-1
#   EB_APPLICATION_NAME: Docker
#   EB_ENVIRONMENT_NAME: Docker-env
#   S3_DOWNLOAD_BUCKET: elasticbeanstalk-ap-northeast-1-365292474125

jobs:
  deploy:
    runs-on: [self-hosted]
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build -t neoimpweb/docker-react-image -f Dockerfile.dev .
    
    - name: Test the Docker image
      run: | 
        docker run -e CI=true neoimpweb/docker-react-image npm run test

    - name: Stop the old one
      run: | 
        docker stop neoimpweb/docker-react-container || true
        docker rm neoimpweb/docker-react-container || true
      
    - name: Run Docker container
      run: |
        docker run -d -p 80:80 --name neoimpweb/docker-react-container neoimpweb/docker-react-image
